### ISSUE TITLE
好像没啥用啊，假如没有字幕文件，这个还能翻译吗

### ISSUE THREAD

**Issue by ghost** [gnh1201/potplayer-lingva#2]
我观看live的话，并不起作用

**Comment by gnh1201** [comment]
Hi

Your problem may be due to the slow response of the primary server. Use a different Lingva Translate server or run your own server.

**Comment by gnh1201** [comment]
And there must be original subtitles. This is an automatic translation tool, not an automatic subtitle download tool.
