### ISSUE TITLE
Pot player not load it after I have copied two files into directory.

### ISSUE THREAD

**Issue by HumanMus1c** [gnh1201/potplayer-lingva#9]
Pot player not load it after I have copied two files into directory.
![image](https://github.com/user-attachments/assets/852579f1-6b7a-42e3-8d26-f6c49b96e3b7)

**Comment by gnh1201** [comment]
Hello, I recently fixed this bug. Could you test it with the latest version?

**Comment by gnh1201** [comment]
Solved

**Comment by HumanMus1c** [comment]
Yes, It's working. Thanks.
